version: '3'
services:

  myapp:
    container_name: flamme_rouge-container
    pull_policy: build
    ports:
      - 3000:3000
    command: "serve ./build"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  esm-server:
    container_name: esm-server-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: "node -r esm build/server/server.js"
    restart: unless-stopped