version: '3'
services:

  # game-app:
  #   container_name: game-container
  #   working_dir: /app
  #   pull_policy: build
  #   ports:
  #     - "3000:3000"
  #   command: "serve -s build"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   networks:
  #   - my-network

  esm-server:
    container_name: esm-server-container
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    command: "node -r esm ./build/server/server.js"
    restart: unless-stopped
    networks:
    - my-network

networks:
  my-network:
